# --- Colores Principales ---
foreground            #dde4e2
background            #0e1514
selection_foreground  #1b3533
selection_background  #b0ccc9
url_color             #80d5cf
cursor                #dde4e2
cursor_text_color     #bec9c7

# --- Paleta de 16 Colores ---

# Black
color0  #4c4c4c
color8  #262626

# Red
color1  #ac8a8c
color9  #c49ea0

# Green
color2  #9195ca
color10 #9eb8c4

# Yellow
color3  #aca98a
color11 #c4c19e

# Blue (Tu color destacado/Cyan-ish)
color4  #80d5cf
color12 #a39ec4

# Magenta
color5  #ac8aac
color13 #c49ec4

# Cyan
color6  #8aacab
color14 #9ec3c4

# White
color7  #f0f0f0
color15 #e7e7e7

background_opacity 0.7