# --- COLORES DE ALTO CONTRASTE (MODO CLARO REAL) ---
# Texto: Negro puro para legibilidad total
foreground            #000000
# Fondo: Gris cemento suave (evita el brillo excesivo del blanco)
background            #c8ced6
# Selección: Invertida (Texto fondo, Fondo negro)
selection_foreground  #c8ced6
selection_background  #000000

# Cursor y URL (Negros para que resalten)
cursor                #000000
cursor_text_color     #c8ced6
url_color             #0000ee

# --- PALETA ANSI (Tonos oscuros y saturados) ---

# Black / Grey
color0  #000000
color8  #444444

# Red
color1  #aa0000
color9  #cc0000

# Green
color2  #007700
color10 #228b22

# Yellow
color3  #8a7200
color11 #c4a000

# Blue
color4  #0000aa
color12 #0000ee

# Magenta
color5  #75507b
color13 #ad7fa8

# Cyan
color6  #06989a
color14 #34e2e2

# White
color7  #eeeeee
color15 #ffffff

background_opacity 0.95