# --- Tipografía ---
font_family      GeistMono Nerd Font Mono
font_size        10
disable_ligatures no

# --- Comportamiento de Shell ---
shell            zsh 
shell_integration enable
confirm_os_window_close 0

# --- Estética de Ventana ---
remember_window_size   no
initial_window_width   950
initial_window_height  500
window_padding_width   10
hide_window_decorations yes
background_opacity     0.7
dynamic_background_opacity yes

# --- Cursor y Scroll ---
cursor_blink_interval  0.5
cursor_stop_blinking_after 1
cursor_trail           0
scrollback_lines       2000
wheel_scroll_min_lines 1

# --- Multimedia y Otros ---
enable_audio_bell      no
url_style              curly
sync_to_monitor        no

# --- Temas y Colores ---
include colors.conf
include theme.conf

# --- Bordes Internos (Solo para splits de Kitty) ---
window_border_width    1pt
active_border_color    #ffffff
inactive_border_color  #222222
