[main]
font=SpaceMono Nerd Font:style=Semibold:size=12
prompt="󰍉 "
icon-theme=Papirus-Dark
icons-enabled=yes
terminal=kitty
width=35
horizontal-pad=20
vertical-pad=15
inner-pad=10
line-height=20
fields=name,generic,comment,executable

[colors]
# Fondo blanco hueso con 85% de opacidad (f2f4f8d9)
background=f2f4f8d9
# Texto gris oscuro
text=5c6773ff
# Match en un azul destacado
match=2d7edbff
# Selección gris claro
selection=d1d5dde6
selection-text=2e3440ff
selection-match=2d7edbff
# Borde gris suave
border=d1d5ddff

[border]
width=2
radius=15