set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on

set -g default-terminal "tmux-256color"
set -aserial-features ",xterm-256color:RGB"

set -g base-index 1
setw -g pane-base-index 1

bind r source-file ~/.tmux.conf \

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Barra de estado simple
set -g status-style bg=default,fg=white
set -g status-left '#[fg=green]#S '
set -g status-right '#[fg=yellow]%H:%M #[fg=blue]%d-%b'